### ISSUE TITLE
TypeError: ufunc 'isnan' not supported for the input types, 

### ISSUE THREAD

**Issue by MIriamastro** [astropenguin/ndradex#4] opened 2019-07-17 14:23 UTC
UPDATE: I changed in File `"/home/user/.local/lib/python3.6/site-packages/ndradex/grid.py", line 228, `  where is said if np.any(np.isnan(coord)): I wrote `if np.any(pd.isnull(coord)) `, and seems like it's fixed it.

------------------------------------------------------------------------------------------------------------------------------
I'm running ndradex, with spyder,
and I get the following error:

`100%|██████████| 1/1 [00:00<00:00, 27.19it/s]

Traceback (most recent call last):

  File "<ipython-input-10-6940d4979d03>", line 1, in <module>
    runfile('/media/user/radex/prueba_pyradex.py', wdir='/media/user/radex')

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/media/user/radex/prueba_pyradex.py", line 11, in <module>
    ds = nd.run('co', '1-0', 100, 1e15, 1e3)

  File "/home/user/.local/lib/python3.6/site-packages/ndradex/utils.py", line 30, in wrapper
    return func(*bound.args, **bound.kwargs)

  File "/home/user/.local/lib/python3.6/site-packages/ndradex/grid.py", line 169, in run
    return finalize(dataset, squeeze)

  File "/home/user/.local/lib/python3.6/site-packages/ndradex/grid.py", line 228, in finalize
    if np.any(np.isnan(coord)):

  File "/home/user/.local/lib/python3.6/site-packages/xarray/core/arithmetic.py", line 69, in __array_ufunc__
    dask='allowed')

  File "/home/user/.local/lib/python3.6/site-packages/xarray/core/computation.py", line 969, in apply_ufunc
    keep_attrs=keep_attrs)

  File "/home/user/.local/lib/python3.6/site-packages/xarray/core/computation.py", line 217, in apply_dataarray_vfunc
    result_var = func(*data_vars)

  File "/home/user/.local/lib/python3.6/site-packages/xarray/core/computation.py", line 564, in apply_variable_ufunc
    result_data = func(*input_data)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

How can I fix this?

**Comment by astropenguin** [comment] 2019-08-01 05:32
Hi @MIriamastro, thank you for using ndRADEX! I think that the workaround (replacing `np.isnan` with `pd.isnull`) is correct but unfortunately I could not reproduce the error if I run the code `ds = nd.run('co', '1-0', 100, 1e15, 1e3)` in my environment (Google Colaboratory). Before fixing it, could you tell me a little more in detail about the code you ran and your environment?

**Comment by MIriamastro** [comment] 2019-08-01 10:43
Hi @astropenguin .
I run the code in spyder3, python 3.6.8, on ubuntu 18.04.

**Comment by astropenguin** [comment] 2019-08-07 02:36
Hi @MIriamastro, thank you for sharing your environment. I found that the TypeError in ndRADEX was caused by a bug of xarray whose version is v0.12.2 or later (released a month ago). This bug changes the dtype of some coordinates, which is an unexpected behavior in ndRADEX.

- [REGRESSION: copy\(deep=True\) casts unicode indices to object · Issue \#3094 · pydata/xarray](https://github.com/pydata/xarray/issues/3094)
- [Fix regression: IndexVariable\.copy\(deep=True\) casts dtype=U to object by crusaderky · Pull Request \#3095 · pydata/xarray](https://github.com/pydata/xarray/pull/3095)

It seems that the bug will be fixed in the next version of xarray (v0.12.4?), so could you please keep using xarray v0.12.1 or earlier to avoid that behavior until the next xarray is released?

**Comment by astropenguin** [comment] 2019-09-03 03:14
Hi @MIriamastro, I released ndRADEX v0.2.0, in which I stop using xarray v0.12.2 or v0.12.3. I hope upgrading ndRADEX (e.g., `pip install -U ndradex`) will fix your problem.

**Closed** 2019-09-25 03:06 UTC
